version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd ./frontend
      - npm install
      - cd ../backend
      - npm install
  build:
    commands:
      - cd ../frontend
      - npm run build:prod
      - cd ../backend
      - npm run deploy
  post_build:
    commands:
      - aws s3 sync ../frontend/dist/davidespinosa s3://$BUCKET_NAME --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"